language: python

python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"

install:
  - pip install -r requirements.txt
  - pip install codecov coverage

script:
  - nosetests -v --with-coverage --cover-package=student_portal_crawler

after_success:
  - codecov

notifications:
  email: false
  slack:
    secure: npdNlesznnxrC7KsuB7sjIkngub2qK/octEycHXGlPUjFCW5gCxMSXSqo8I68DRIEBzQ6a9Dje/6ueRfmGFMsphKQEzdeNjN1XdCfq6A1kz6f6tABj0v8oXyq7jgUwfpwOVhDMDo7L1kvUKvMiMcFUi7qXzxs1Tboku2OsG++JiPVjLDxF9x/xWmtVqarTZxFxa7Z1DBsXh7pZ3eYia7+jIWdcp22DTOf4LvxsyfDl7h30G8JZlC7jkymp0ZJXtECz4eTUa4eQ73O5GaiOv5KfzH7bB9gY72vmD+HxPMOjnKgxS7hBol6hBbwTlIYHtedB2INevuVZoQvPLEy+kZdfcZv+liJhd/ofLMfey9QZ877vVzZgi2DGW2ul6WWeddKvo56vqOlLsk8SxyxeLT/eBGDqL71VomdblfCLOrFMhHI9hbxvr2DXyUfM0hoUxsP1JwloK7hCLVnvqK6uhaVrRkyb+qB10Qz2Iwsw/6WRmgZWbtYd/QyxtfB01+vvS2a8E2uTDHV3eENPbMSLKFHhH5gkij0zkXwfgC91iVkNFfkvUOZ6cyKTxHwZPDVSeJbMpov76t08fJWa5xmTSI4Nl26eYEdz9W5caxXuo8SfacCCg64/HAKNfAgAiMqCOpWRp/kuhWP5iEas5FRv3VunN2xrCoWhnbxRmP6YKmZxQ=
